set hlsearch
" set clear and nice vim colorscheme "
syntax on
colorscheme desert256
set t_Co=256

" sets tabstop "
set tabstop=2

" sets tabwidth "
set shiftwidth=2

" sets autocommenting of following lines "
set formatoptions=rco

set nu

"mkdir -p ~/.vim/colors"
"curl -o ~/.vim/colors/desert256.vim https://raw.githubusercontent.com/vim-scripts/desert256.vim/master/colors/desert256.vim"
