" set clear and nice vim colorscheme "
colorscheme slate

" sets smartindentation "
set si

" sets vim autoindentation "
set ai

"sets vim folding, based on expression, comment folding enabled "
set fdm=expr foldexpr=getline(v:lnum)=~'^\s*'.&commentstring[0] 

" sets tabstop "
set tabstop=3

" sets tabwidth "
set shiftwidth=3

" sets autocommenting of following lines "
set formatoptions=rco

